#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

if ! which autocorrect >/dev/null; then
  echo "Error: autocorrect is not installed." >&2
  exit 1
fi

autocorrect -V && find . -name *.md | xargs autocorrect --lint
